### PR TITLE
Update version to 0.9

### PR DESCRIPTION
**Pull request by nsorros**
Updates remote version to 0.9 which adds
`remote jobs` to list sagemaker jobs

### CODE REVIEW

**Comment by nsorros** [comment]
@ivyleavedtoadflax can try `brew upgrade remote` to ensure this work on your end and then approve

**Review by aCampello — COMMENTED** [review]
`brew upgrade remote` tells me:

```bash
(env) ➜  ~ brew upgrade remote
Warning: wellcometrust/wellcome-tap/remote 0.8 already installed
```

Probably 0.9 will only show in the remote tap once merged?

If I build directly from source (`brew upgrade --build-from-source ./remote.rb`), the new command works:

```
|  mesh-cnn-2021-02-0-2021-06-11-07-41-00-749       |  InProgress |
etc..
```

**Comment by nsorros** [comment]
> `brew upgrade remote` tells me:
> 
> ```shell
> (env) ➜  ~ brew upgrade remote
> Warning: wellcometrust/wellcome-tap/remote 0.8 already installed
> ```
> 
> Probably 0.9 will only show in the remote tap once merged?
You are right

> If I build directly from source (`brew upgrade --build-from-source ./remote.rb`), the new command works:
> 
> ```
> |  mesh-cnn-2021-02-0-2021-06-11-07-41-00-749       |  InProgress |
> etc..
> ```

This is how I tested it as well

**Comment by nsorros** [comment]
I assume you wanted to approve @aCampello

**Comment by ivyleavedtoadflax** [comment]
> @ivyleavedtoadflax can try `brew upgrade remote` to ensure this work on your end and then approve

Sorry late to the party here. I actually tend to install manually as I didn't bother to install brew after the last format

**Pull request merged**
